### ISSUE TITLE
Add a license model

### ISSUE THREAD

**Issue by DonBrus** [art103/JZ-F407VET6#3]
@art103 Hi Richard, would it be possible for you to specify a license model you'd like to apply for this project? I'd like to use parts of it and give proper credit/get proper authorization to use your excellent work.

Thanks.

**Comment by art103** [comment]
Hi @DonBrus,
Thank you, and I'm glad you have found it useful!

The majority of the code is generated by STM's CubeMX tool. I just set the correct config options and added some glue code :-).
There are multiple licenses from multiple SW projects, with individual .c and .h files containing their respective licenses.
I have not added any restrictions on the small amount of code I have added and the standard STM license is in those generated files (i.e. provided AS-IS).
I can't add a global (top level) LICENSE file, as I do not have the authority to modify the license terms of individual projects pulled in by STM CubeMX.

I'm not a legal expert and there are several topics discussing the use of STM32CubeMX generated output on Reddit, Forums, etc.
I've provided the .ioc file, so you should be able to generate a clean set of code and do your due diligence from the documentation and licenses provided by CubeMX.

**Comment by DonBrus** [comment]
Hey @art103 thank you for your response. If this sits fine with you I'll then give credit in my project to your original work as a link to your repo. Does that sound ok?

**Comment by art103** [comment]
Sounds good to me.
The more people using it, hopefully the better / more stable we can get the platform 👍

**Comment by DonBrus** [comment]
Great! :+1: 
Thanks again for your help.
